### PR TITLE
Implemented literally everything

### PR DESCRIPTION
**Pull request by ashmind**
This CR includes full implementation of PowerShell mode, down to string interpolation (except in here-strings) and highlighting of built-in functions/variables.

Due to the list of built-ins, the mode is rather large, though if there are complaints it is always possible to generate one without built-ins.

### CODE REVIEW

**Comment by Dominator008** [comment]
@ashmind Can you consider contributing back to CodeMirror (https://github.com/codemirror/CodeMirror) directly?

**Comment by ashmind** [comment]
@Dominator008 Sure, I'll do that when I have a moment.

**Comment by ashmind** [comment]
@Dominator008 Just done a PR (codemirror/CodeMirror#3910).

**Comment by Dominator008** [comment]
@ashmind Great thanks!

**Pull request closed without merging**
